FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    build-essential \
    gcc \
    libc6-dev \
    linux-headers-generic \
    net-tools \
    iputils-ping \
    vim \
    sudo

WORKDIR /app
COPY src /app

RUN make

RUN chmod +x /app/server-app

CMD ["/app/server-app"]